### ISSUE TITLE
AWS S3 集成

### ISSUE THREAD

**Issue by aqbjteddy** [thebluedoc/bluedoc#114]
@huacnlee @griffinqiu 
Hi, bluedoc使用了一半，现在需要考虑备份问题，我在production.env上面看到了可以把存储放到aws s3上去，更改了以下配置信息：

```
STORAGE_SERVICE=amazon
AWS_ACCESS_KEY_ID=xxx
AWS_SECRET_ACCESS_KEY=xxx
AWS_S3_REGION=us-east-1
AWS_S3_BUCKET=xxx
```

重新启动了docker container，但是在s3中没有发现任何文件，查了production.log，没有发现异常信息以及相关的info日志。

还有个问题，之前在local里的文件会自动到s3上吗？

**Comment by huacnlee** [comment]
之前传本地的文件你得重新传或手动调整同步到 S3，不会自动到 S3 上去的。

**Comment by huacnlee** [comment]
如果你已经有很多内容存储在本地了，可以试试用 AWS Cli 的工具同步试试，这个事情我还没做过

**Comment by aqbjteddy** [comment]
@huacnlee 好的，谢谢，那我应该怎么在服务上查看是不是成功同步到s3了，是不是已经配置成功了？

**Comment by huacnlee** [comment]
同步你要自己做，和 BlueDoc 服务没关系，参考 https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html

你要看服务的 S3 存储有没有配置成功，可以配置好 S3 以后上传一张图片试试。

**Comment by aqbjteddy** [comment]
@huacnlee 好的，我明白了，我的意思是，有没有什么地方可以让我确认下，production.env里的STORAGE_SERVICE=amazon可以成功在bluedoc中工作的？
