### ISSUE TITLE
使用docker安装后，不能访问安装界面

### ISSUE THREAD

**Issue by winecos** [thebluedoc/bluedoc#61]
参照 doc\docker _install.md文档说明，安装成功后，并不能访问安装界面。
其中，我修改了
ocker run --detach \
             --name bluedoc \
             **--publish 443:443 --publish 80:80 \**  --> 4433 ,8089 

**问题：**
1.修改访问端口：80到8089，有影响么？
2.443端口被其他程序占用，不能使用，一定要使用443么？

谢谢。

另：项目非常棒！

**Comment by huacnlee** [comment]
这个是专业版功能，Docker 不含这部分，今天晚些时候我会补充一下 Docker 方式的配置方法

**Comment by winecos** [comment]
或者，提供下非docker得配置方法也okay, 服务器是centos.
部署得文档不太清晰。

**Comment by huacnlee** [comment]
@winecos https://bluedoc.io/bluedoc/help-cn/install 配置方式文档更新进去了

**Comment by winecos** [comment]
> 或者，提供下非docker得配置方法也okay, 服务器是centos.
> 部署得文档不太清晰。

感谢 ！
另外，可以改变 --publish 443:443 --publish 80:80 \ 么？
自定义访问端口
