### ISSUE TITLE
docker 本地部署运行问题

### ISSUE THREAD

**Issue by izayl** [thebluedoc/bluedoc#84]
**1. 进行上传头像操作，头像资源链接有误**

头像的链接变成了 http://localhost/uploads/1ff7ukqsjv1jx6mhktk3d0g4dvfj?s=large

写死的 localhost？

实际是绑定了域名的

**2. 修改邮箱没有发送邮件**

**Comment by huacnlee** [comment]
配置 APP_HOST 详见 bluedoc.io 上的文档
