### ISSUE TITLE
Docker install instructions do not work (Demo video attached)

### ISSUE THREAD

**Issue by vikaskedia** [thebluedoc/bluedoc#85]
The container restarts every 30 seconds and refuses connections on port 80

I recorded a video of the docker logs -f so you can better debug.

https://www.youtube.com/watch?v=nt2owDDOGXI

**Comment by huacnlee** [comment]
I watched the video. In your video, the BlueDoc docker services has been started, there is no errors.

This is looks like you don't get a correct IP address for the docker.

If your Docker Machine in local, you just need visit http://127.0.0.1
