### ISSUE TITLE
编辑器内容插入代码块仅有一行的时候不正常显示

### ISSUE THREAD

**Issue by F00cked** [thebluedoc/bluedoc#86]
编辑器内容插入代码块仅有一行的时候不正常显示，浏览文档正常显示，如下两图所示。
编辑器显示：
<img width="813" alt="屏幕快照 2019-06-21 下午3 59 27" src="https://user-images.githubusercontent.com/2917497/59907434-a396dd80-943d-11e9-822c-73a8e04cafac.png">

文档显示：
<img width="774" alt="屏幕快照 2019-06-21 下午3 59 34" src="https://user-images.githubusercontent.com/2917497/59907441-a7c2fb00-943d-11e9-9e5c-20f3ff9efd25.png">

**Comment by F00cked** [comment]
docker 镜像：bluedoc/bluedoc:latest

**Comment by huacnlee** [comment]
哦，看起来是被浏览器滚动条挡住了
